## imports

In [1]:
import pandas as pd

In [2]:
df_librarie = pd.read_excel('data/excelfiles/Urheber und Reihen.xlsx', sheet_name='Recherche', header=0)

#df_blatter = pd.read_feather('data/feather/df_neuheiten_blatter.feather')
df_buchhaus = pd.read_feather('data/feather/df_neuheiten_buchhaus.feather')

## Data Wrangling Urheber und Reihen

In [3]:
df_librarie

                 1. Urheber                       Alle Reihen
0                       NaN                      Asterix ; 20
1                       NaN                               NaN
2         May, Werner Jakob                               NaN
3      Schwaar, Hans Ulrich                               NaN
4          Engel, Franziska                               NaN
...                     ...                               ...
13723                   NaN  Schweizer Illustrierte ; 16/2023
13724                   NaN        Schweizer Garten ; 05/2023
13725       Guzowska, Marta                               NaN
13726      Gilbert, Lindsay                               NaN
13727       Bradford, Chris                Die Soul-Reihe ; 1

[13728 rows x 2 columns]

In [4]:
# add new column to df_libarie with the second element in alle reihen after the semicolon
df_librarie['Reihe'] = df_librarie['Alle Reihen'].str.split(';').str[1]
df_librarie['Auflage'] = df_librarie['Alle Reihen'].str.split(';').str[0]

df_librarie = df_librarie[['1. Urheber', 'Auflage', 'Reihe']]

In [5]:
df_librarie.tail(10)

,1. Urheber,Auflage,Reihe
13718,NaN,Schweizer Familie,16/2023
13719,"Geisler, Dagmar",NaN,NaN
13720,NaN,GEOlino: Die Welt für junge Entdeckerinnen und...,05/2023
13721,NaN,MERIAN : Die Lust am Reisen,23/2023
13722,"Evans, Cathy",NaN,NaN
13723,NaN,Schweizer Illustrierte,16/2023
13724,NaN,Schweizer Garten,05/2023
13725,"Guzowska, Marta",NaN,NaN
13726,"Gilbert, Lindsay",NaN,NaN
13727,"Bradford, Chris",Die Soul-Reihe,1

## Datawrangling all scraped df

In [6]:
df_buchhaus.head()

,Titel,Preis,Autor,Genre,Text,ISBN/GTIN,Produktart,Einbandart,Verlag,Erscheinungsdatum,Auflage,Reihe,Seiten,Sprache,Masse,Artikel-Nr.
0,Atlas - Die Geschichte von Pa Salt,32.00,"Riley, LucindaWhittaker, HarryHauser, SonjaÜbe...",belletristik romane,"Paris, 1928. Ein Junge wird gerade noch rechtz...",978-3-442-31567-3,Buch,Gebunden,Goldmann,11.05.2023Erstverkaufstag11.05.2023,Deutsche Erstausgabe,n-Nr.08,,None,None,None
1,Der Feind,24.90,"Brand, Christine",belletristik krimi,Ein bizarre Mordserie an Männern sowie Schüsse...,978-3-7645-0771-8,Buch,Paperback,Blanvalet,26.04.2023,1. A.,n-Nr.05,,Deutsch,None,None
2,Die Krume Brot,29.00,nan,belletristik schweizer,"Adelina, Tochter italienischer Einwanderer, ar...",978-3-498-00320-3,Buch,Gebunden,Rowohlt,18.04.2023,,None,,Deutsch,"Breite 133 mm, Höhe 209 mm, Dicke 23 mmGewicht...",None
3,Anuschka und Finn,20.00,"Schawinski, Roger",fachbuecher geschichte schweiz,"Roger Schawinski über einen Medienskandal, der...",978-3-033-09890-9,Buch,Paperback,Radio 1 AG,12.05.2023,None,None,,Deutsch,"Breite 144 mm, Höhe 221 mm, Dicke 15 mmGewicht...",58408389
4,Elternabend,23.90,"Fitzek, Sebastian",belletristik romane,Stell dir vor ...\n... du musst eine halbe Ewi...,978-3-426-28413-1,Buch,Paperback,Droemer/Knaur,26.04.2023Erstverkaufstag26.04.2023,,None,,Deutsch,"Breite 135 mm, Höhe 210 mm, Dicke 25 mm",None

In [7]:
df = df_buchhaus

## Book analysis

In [8]:
# autors which have new books on the market and are in the librarie
interresting_books = df[df['Autor'].isin(df_librarie['1. Urheber'])]
interresting_books.head()

,Titel,Preis,Autor,Genre,Text,ISBN/GTIN,Produktart,Einbandart,Verlag,Erscheinungsdatum,Auflage,Reihe,Seiten,Sprache,Masse,Artikel-Nr.
1,Der Feind,24.90,"Brand, Christine",belletristik krimi,Ein bizarre Mordserie an Männern sowie Schüsse...,978-3-7645-0771-8,Buch,Paperback,Blanvalet,26.04.2023,1. A.,n-Nr.05,,Deutsch,None,None
4,Elternabend,23.90,"Fitzek, Sebastian",belletristik romane,Stell dir vor ...\n... du musst eine halbe Ewi...,978-3-426-28413-1,Buch,Paperback,Droemer/Knaur,26.04.2023Erstverkaufstag26.04.2023,,None,,Deutsch,"Breite 135 mm, Höhe 210 mm, Dicke 25 mm",None
10,Das Café ohne Namen,34.90,"Seethaler, Robert",belletristik romane,"Ein Café und seine Menschen. Ein Mann, der sei...",978-3-546-10032-8,Buch,Gebunden,,26.04.2023,,None,,Deutsch,"Breite 128 mm, Höhe 210 mm, Dicke 28 mmGewicht...",None
11,Mit dem Mut zur Liebe,19.90,"Lind, Hera",taschenbuch romane,"Erst ein dramatischer Unfall, dann die waghals...",978-3-426-52840-2,Taschenbuch,Paperback,Droemer/Knaur,02.05.2023,,None,,Deutsch,"Breite 125 mm, Höhe 190 mm, Dicke 36 mmGewicht...",None
12,Gnadenlose Provence,25.90,"Lagrange, Pierre",belletristik krimi,Eine gnadenlose Tat erschüttert die Provence -...,978-3-651-02592-9,Buch,Paperback,FISCHER Scherz,26.04.2023,,n-Nr.08,,Deutsch,None,None

In [9]:
# Reihen which have new books on the market and are in the librarie
df[df['Reihe'].isin(df_librarie['Reihe'])]

Empty DataFrame
Columns: [Titel, Preis, Autor, Genre, Text, ISBN/GTIN, Produktart, Einbandart, Verlag, Erscheinungsdatum, Auflage, Reihe, Seiten, Sprache, Masse, Artikel-Nr.]
Index: []

## export

In [10]:
interresting_books.reset_index(drop=True, inplace=True)

interresting_books.to_excel('data/excelfiles/df_interresting_books.xlsx', index=False)
interresting_books.to_feather('data/feather/df_interresting_books.feather')

## Ausblick

Weitere Informationen:

* Buchtitel der bestehenden Bücher um doppelte bücher zu erkennen